import type { components } from '../../../anakata-ui/app/types/api'

export type {
  AllowedTransition,
  Booking,
  BookingAuditRow,
  BookingFormOptions,
  BookingListItem,
  BookingOwner,
  BookingRequestSummary,
  BookingSegment,
  BookingStatus,
  BookingQuote,
  BookingQuoteRequest,
  BookingType,
  ChannelOfOrigin,
  ChangeHistoryEntry,
  Contact,
  CreateReservationRequest,
  CreateReservationResponse,
  Group,
  GroupSummary,
  MainChannel,
  MovePreview,
  Paginated,
  PreferredChannel,
  PriceLine,
  BusinessRulesDocument,
  BusinessRulesVersion,
  CancellationBand,
  ConfigChange,
  ConfigPublisher,
  ConfigValidation,
  ConfigVersion,
  ConfigVersionDetail,
  ConfigVersionSummary,
  ConfigWarning,
  AvailabilityCounts,
  BlockClaim,
  BlockReason,
  CabinAvailability,
  CabinUnavailableError,
  CabinState,
  CalendarCell,
  CalendarDeparture,
  CalendarGrid,
  CalendarRow,
  ClaimHolder,
  ClaimSummary,
  Departure,
  DepartureKpis,
  DepartureListItem,
  DepartureLocks,
  DepartureMutationResponse,
  DepartureStatus,
  EngineLabel,
  EngineLabelTone,
  EngineSettingsDocument,
  EngineSettingsValidation,
  EngineSettingsVersion,
  GenerateSeasonResult,
  HoldType,
  InternalBlock,
  Itinerary,
  ItineraryCompleteness,
  ItineraryDefaults,
  ItineraryGradient,
  ItineraryListItem,
  ItineraryPair,
  ItineraryStatus,
  Me,
  NoRate,
  PermissionItem,
  PriceCheckRow,
  Quote,
  RatesDocument,
  RatesVersion,
  Role,
  RuleGroup,
  RuleRegistryCounts,
  RuleRegistryRow,
  RuleStatus,
  RuleWhere,
  UserListItem,
  Yacht
} from '../../../anakata-ui/app/types'

export type Permission = components['schemas']['Permission']
export type UserStatus = components['schemas']['UserStatus']
export type InviteUserRequest = components['schemas']['InviteUserRequest']
export type UpdateUserRequest = components['schemas']['UpdateUserRequest']
export type DisableUserRequest = components['schemas']['DisableUserRequest']
export type StoreRoleRequest = components['schemas']['StoreRoleRequest']
export type UpdateRoleRequest = components['schemas']['UpdateRoleRequest']
